# Boolean enable/disable
discord_entry_webhook_enabled: True
discord_exit_webhook_enabled: True

# Channel webhooks to send confirmed entries
discord_entry_webhook: 'https://discord.com/api/webhooks/1113775631243694100/3rsIS9y4fG56jpRibOXOCGaPEICZnrYnstzS-qg6Id4VL-waQn_jdqFtInJLCtcW3Ww3'
discord_exit_webhook: 'https://discord.com/api/webhooks/1114687425592180826/fmyCST3Y1wtivGEL4E06CVZKzoth40GFNfuuR3Y_DIkawCHrQ51blMXnVepzXzxvgSfe'

# trade cap per trade book
trade_cap: 10

# Send trade book delay (seconds)
trade_book_wait: 10

entry_strategy_1:
  liquidation: 1
  zscore: 0.1
  webhook: 'https://discord.com/api/webhooks/1113921479294324746/jxDojPwSw6Y4xKkLD4KtORWsMI_fLfDqUb9amXmxLxm3MwVcehFXbJpA8SuKk3D1sqKA'
entry_strategy_2:
  liquidation: 1
  zscore: 0.1
  webhook: 'https://discord.com/api/webhooks/1116053899921588236/Iyc7rmx7hLX4flfmTrwQ7ZpXCykLztQFaW7-y_zwuvQhzNAdyfuqp6ChId6ukSPNbl8q'

# Z-Score timeframes for use in volume analysis
# Supported values: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h
zscore_timeframes:
  - 1m
  - 3m
  - 5m
  - 15m
  - 30m
  - 1h
  - 2h
  - 4h

# Candles to look back for Z-Score calculation
zscore_period: 27

# Exclude symbols from analysis
excluded_symbols:
  - NONEUSDT

# Exclude all symbols with quote
excluded_quote:
  - BUSD

# Select Leverage
leverage: 10
