# Boolean enable/disable
discord_webhook_enabled: True
discord_webhook_2_enabled: True
# Channel webhooks to send confirmed entries
discord_webhook: 'https://discord.com/api/webhooks/1113775631243694100/3rsIS9y4fG56jpRibOXOCGaPEICZnrYnstzS-qg6Id4VL-waQn_jdqFtInJLCtcW3Ww3'
discord_webhook_2: 'https://discord.com/api/webhooks/1113921479294324746/jxDojPwSw6Y4xKkLD4KtORWsMI_fLfDqUb9amXmxLxm3MwVcehFXbJpA8SuKk3D1sqKA'

filters:
  # liquidation to exceed
  liquidation: 1
  # Z-Score to exceed
  zscore: 0.1

# Z-Score timeframes for use in volume analysis
# Supported values: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h
zscore_timeframes:
  - 1m
  - 3m
  - 5m
  - 15m
  - 30m
  - 1h
  - 2h
  - 4h

# Candles to look back for Z-Score calculation
zscore_lookback: 27

# Exclude symbols from analysis
excluded_symbols:
  - COMBOUSDT
